name: "technology_config"
description: "This plant has wind connected to a ocean alkalinity enhancement device"

technologies:
  wind:
    performance_model:
      model: "FlorisWindPlantPerformanceModel"
    cost_model:
      model: "ATBWindPlantCostModel"
    model_inputs:
      performance_parameters:
        num_turbines: 3 #number of turbines in the farm
        hub_height: 80.0 # turbine hub-height
        operational_losses: 12.83 #percentage of non-wake losses
        floris_wake_config: !include "floris_v4_default_template.yaml" #floris wake model file
        floris_turbine_config: !include "floris_turbine_GE_1.5MW.yaml" #turbine model file formatted for floris
        resource_data_averaging_method: "weighted_average" #"weighted_average", "average" or "nearest"
        operation_model: "cosine-loss" #turbine operation model
        default_turbulence_intensity: 0.06
        enable_caching: True #whether to use cached results
        cache_dir: "cache" #directory to save or load cached data
        layout:
          layout_mode: "basicgrid"
          layout_options:
            row_D_spacing: 5.0
            turbine_D_spacing: 5.0
            rotation_angle_deg: 0.0
            row_phase_offset: 0.0
            layout_shape: "square"
      cost_parameters:
        capex_per_kW: 1380.0
        opex_per_kW_per_year: 29.0
        cost_year: 2022
  oae:
    performance_model:
      model: "ocean_alkalinity_enhancement_performance"
    finance_model:
      model: "ocean_alkalinity_enhancement_cost_financial"
    model_inputs:
      performance_parameters:
        number_ed_min: 1
        number_ed_max: 10
        max_ed_system_flow_rate_m3s: 0.0324 # m^3/s
        frac_base_flow: 0.5
        assumed_CDR_rate: 0.8 # mol CO2/mol NaOH
        use_storage_tanks: True
        initial_tank_volume_m3: 0. #m^3
        store_hours: 12. # hours
        acid_disposal_method: "sell rca"
        initial_salinity_ppt: 73.76 # ppt
        initial_temp_C: 10.0 # degrees Celsius
        initial_dic_mol_per_L: 0.0044 # mol/L
        initial_pH: 8.1 # initial pH
