name: "technology_config"
description: "This plant has offshore wind and battery connected to a ocean alkalinity enhancement device"

technologies:
  hopp:
    performance_model:
      model: "hopp"
    cost_model:
      model: "hopp"
    dispatch_rule_set:
      model: "pyomo_dispatch_generic_converter"
    model_inputs:
      shared_parameters:
        cost_year: 2022
      performance_parameters:
        cache_dir: "cache"
        enable_caching: True
        hopp_config: !include tech_inputs/hopp_config.yaml
      dispatch_rule_parameters:
        commodity_name: "electricity"
        commodity_storage_units: "kW"
  battery:
    dispatch_rule_set:
      model: "pyomo_dispatch_generic_storage"
    control_strategy:
      model: "heuristic_load_following_controller"
    performance_model:
      model: "pysam_battery"
    cost_model:
      model: "atb_battery_cost"
    model_inputs:
      shared_parameters:
        commodity_name: "electricity"
        max_charge_rate: 50000 #kW
        max_capacity: 200000 #kWh
        n_control_window: 24
        n_horizon_window: 48
        init_charge_percent: 0.9
        max_charge_percent: 1.0
        min_charge_percent: 0.2
        system_commodity_interface_limit: 1e12
      performance_parameters:
        system_model_source: "pysam"
        chemistry: "LFPGraphite"
      cost_parameters:
        cost_year: 2022
        commodity_units: "kW"
        energy_capex: 246 # $/kWh from 2024 ATB year 2025
        power_capex: 317 # $/kW from 2024 ATB year 2025
        opex_fraction: 0.02536510376633359
      control_parameters:
        commodity_storage_units: "kW"
        tech_name: "battery"
      dispatch_rule_parameters:
        commodity_name: "electricity"
        commodity_storage_units: "kW"
  oae:
    performance_model:
      model: "ocean_alkalinity_enhancement_performance"
    cost_model:
      model: "ocean_alkalinity_enhancement_cost"
    model_inputs:
      performance_parameters:
        number_ed_min: 1
        number_ed_max: 10
        max_ed_system_flow_rate_m3s: 0.0324 # m^3/s
        frac_base_flow: 0.5
        assumed_CDR_rate: 0.8 # mol CO2/mol NaOH
        use_storage_tanks: True
        initial_tank_volume_m3: 0. #m^3
        store_hours: 12. # hours
        acid_disposal_method: "sell rca"
        initial_salinity_ppt: 73.76 # ppt
        initial_temp_C: 10.0 # degrees Celsius
        initial_dic_mol_per_L: 0.0044 # mol/L
        initial_pH: 8.1 # initial pH

      cost_parameters:
        mass_product_tonne_yr: 100000.0
