name: "technology_config"
description: "This plant has offshore wind and wave energy connected to a direct ocean capture device"

technologies:
  hopp:
    performance_model:
      model: "hopp"
    cost_model:
      model: "hopp"
    dispatch_rule_set:
      model: "pyomo_dispatch_generic_converter"
    model_inputs:
      shared_parameters:
        cost_year: 2022
      performance_parameters:
        cache_dir: "cache"
        enable_caching: True
        hopp_config: !include tech_inputs/hopp_config.yaml
      dispatch_rule_parameters:
        commodity_name: "electricity"
        commodity_storage_units: "kW"
  battery:
    dispatch_rule_set:
      model: "pyomo_dispatch_generic_storage"
    control_strategy:
      model: "heuristic_load_following_controller"
    performance_model:
      model: "pysam_battery"
    cost_model:
      model: "atb_battery_cost"
    model_inputs:
      shared_parameters:
        commodity_name: "electricity"
        max_charge_rate: 50000 #kW
        max_capacity: 200000 #kWh
        n_control_window: 24
        n_horizon_window: 48
        init_charge_percent: 0.9
        max_charge_percent: 1.0
        min_charge_percent: 0.2
        system_commodity_interface_limit: 1e12
      performance_parameters:
        system_model_source: "pysam"
        chemistry: "LFPGraphite"
      cost_parameters:
        cost_year: 2022
        commodity_units: "kW"
        energy_capex: 246 # $/kWh from 2024 ATB year 2025
        power_capex: 317 # $/kW from 2024 ATB year 2025
        opex_fraction: 0.02536510376633359
      control_parameters:
        commodity_storage_units: "kW"
        tech_name: "battery"
      dispatch_rule_parameters:
        commodity_name: "electricity"
        commodity_storage_units: "kW"
  doc:
    performance_model:
      model: "direct_ocean_capture_performance"
    cost_model:
      model: "direct_ocean_capture_cost"
    model_inputs:
      shared_parameters:
        power_single_ed_w: 24000000. # W
        flow_rate_single_ed_m3s: 0.6 # m^3/s
        number_ed_min: 1
        number_ed_max: 10
        E_HCl: 0.05 # kWh/mol
        E_NaOH: 0.05 # kWh/mol
        y_ext: 0.9
        y_pur: 0.2
        y_vac: 0.6
        frac_ed_flow: 0.01
        use_storage_tanks: True
        initial_tank_volume_m3: 0. #m^3
        store_hours: 12. # hours
        sal: 33. # ppt
        temp_C: 12. # degrees Celsius
        dic_i: 0.0022 # mol/L
        pH_i: 8.1 # initial pH

      cost_parameters:
        infrastructure_type: "new"
