name: "technology_config"
description: "This plant has offshore wind and wave energy connected to a direct ocean capture device"

technologies:
  hopp:
    performance_model:
      model: "HOPPComponent"
    cost_model:
      model: "HOPPComponent"
    dispatch_rule_set:
      model: "PyomoDispatchGenericConverter"
    model_inputs:
      shared_parameters:
        cost_year: 2022
      performance_parameters:
        cache_dir: "cache"
        enable_caching: True
        hopp_config: !include tech_inputs/hopp_config.yaml
      dispatch_rule_parameters:
        commodity_name: "electricity"
        commodity_storage_units: "kW"
  wind:
    performance_model:
      model: "FlorisWindPlantPerformanceModel"
    cost_model:
      model: "ATBWindPlantCostModel"
    model_inputs:
      performance_parameters:
        num_turbines: 22 #number of turbines in the farm
        hub_height: 150.0 # turbine hub-height
        operational_losses: 12.83 #percentage of non-wake losses
        floris_wake_config: !include "floris_v4_default_template.yaml" #floris wake model file
        floris_turbine_config: !include "floris_turbine_osw_15MW.yaml" #turbine model file formatted for floris
        resource_data_averaging_method: "average" #"weighted_average", "average" or "nearest"
        operation_model: "cosine-loss" #turbine operation model
        default_turbulence_intensity: 0.06
        enable_caching: True #whether to use cached results
        cache_dir: "cache" #directory to save or load cached data
        layout:
          layout_mode: "basicgrid"
          layout_options:
            row_D_spacing: 7.0
            turbine_D_spacing: 7.0
            rotation_angle_deg: 0.0
            row_phase_offset: 0.0
            layout_shape: "square"
      cost_parameters:
        capex_per_kW: 9390
        opex_per_kW_per_year: 72
        cost_year: 2022

  combiner:
    performance_model:
      model: "GenericCombinerPerformanceModel"
    dispatch_rule_set:
      model: "PyomoDispatchGenericConverter"
    model_inputs:
      performance_parameters:
        commodity: "electricity"
        commodity_units: "kW"
      dispatch_rule_parameters:
        commodity_name: "electricity"
        commodity_storage_units: "kW"
  battery:
    dispatch_rule_set:
      model: "PyomoRuleStorageBaseclass"
    control_strategy:
      model: "HeuristicLoadFollowingController"
    performance_model:
      model: "PySAMBatteryPerformanceModel"
    cost_model:
      model: "ATBBatteryCostModel"
    model_inputs:
      shared_parameters:
        commodity_name: "electricity"
        max_charge_rate: 50000 #kW
        max_capacity: 200000 #kWh
        n_control_window: 24
        n_horizon_window: 48
        init_charge_percent: 0.9
        max_charge_percent: 1.0
        min_charge_percent: 0.2
        system_commodity_interface_limit: 1e12
      performance_parameters:
        system_model_source: "pysam"
        chemistry: "LFPGraphite"
      cost_parameters:
        cost_year: 2022
        commodity_units: "kW"
        energy_capex: 246 # $/kWh from 2024 ATB year 2025
        power_capex: 317 # $/kW from 2024 ATB year 2025
        opex_fraction: 0.02536510376633359
      control_parameters:
        commodity_storage_units: "kW"
        tech_name: "battery"
      dispatch_rule_parameters:
        commodity_name: "electricity"
        commodity_storage_units: "kW"
  doc:
    performance_model:
      model: "DOCPerformanceModel"
    cost_model:
      model: "DOCCostModel"
    model_inputs:
      shared_parameters:
        power_single_ed_w: 24000000. # W
        flow_rate_single_ed_m3s: 0.6 # m^3/s
        number_ed_min: 1
        number_ed_max: 10
        E_HCl: 0.05 # kWh/mol
        E_NaOH: 0.05 # kWh/mol
        y_ext: 0.9
        y_pur: 0.2
        y_vac: 0.6
        frac_ed_flow: 0.01
        use_storage_tanks: True
        initial_tank_volume_m3: 0. #m^3
        store_hours: 12. # hours
        sal: 33. # ppt
        temp_C: 12. # degrees Celsius
        dic_i: 0.0022 # mol/L
        pH_i: 8.1 # initial pH

      cost_parameters:
        infrastructure_type: "new"
