name: "driver_config"
description: "This analysis runs a hybrid plant to match the first example in H2Integrate"

general:
  folder_output: outputs

recorder:
  # required inputs
  flag: True #record outputs
  file: "cases.sql" #this file will be written to the folder `outputs`

  # optional but recommended inputs
  overwrite_recorder: True #If True, do not create a unique recorder file for subsequent runs. Defaults to False.
  recorder_attachment: "model" #"driver" or "model", defaults to "model". Use "driver" if running a parallel simulation.
  includes: ["*"] #include everything
  excludes: ["*resource_data*"] #exclude resource data

  # below are optional and defaulted to the OpenMDAO default
  # record_inputs: True #defaults to True
  # record_outputs: True #defaults to True
  # record_residuals: True #defaults to True
  # options_excludes: #this is only used if recorder_attachment is "model"
