description: Driver config for CSVGen design of experiments
name: driver_config

general:
  folder_output: ex_27_out
  create_om_reports: false
driver:
  design_of_experiments:
    flag: true
    debug_print: false
    generator: "csvgen"
    filename: "site_wind_solar_doe.csv"
    run_parallel: false
design_variables:
  solar:
    system_capacity_DC:
      flag: true
      lower: 5000.0
      upper: 5000000.0
      units: "kW"
  wind_site.wind_resource:
    latitude:
      flag: True
      units: "deg"
      lower: -90.0
      upper: 90.0
    longitude:
      flag: True
      units: "deg"
      lower: -180.0
      upper: 180.0
  solar_site.solar_resource:
    latitude:
      flag: True
      units: "deg"
      lower: -90.0
      upper: 90.0
    longitude:
      flag: True
      units: "deg"
      lower: -180.0
      upper: 180.0

objective:
  name: finance_subgroup_electricity.LCOE
recorder:
    file: cases.sql
    overwrite_recorder: true
    flag: true
    includes: ['*']
    excludes: ['*river_resource_data']
